// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OmnisRouter.Store;

#nullable disable

namespace OmnisRouter.Store.Migrations.Sqlite.Migrations
{
    [DbContext(typeof(OmnisRouterDbContext))]
    [Migration("20260819153139_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("OmnisRouter.Core.Routing.DecisionLogEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChosenModelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ChosenProvider")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientFormat")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClusterId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<int>("Decision")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EstCostDeltaVsBigUsd")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("EstCostUsd")
                        .HasColumnType("decimal(18,8)");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Margin")
                        .HasColumnType("REAL");

                    b.Property<int>("Outcome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Reason")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SessionPinApplied")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<double>("Top1Sim")
                        .HasColumnType("REAL");

                    b.Property<double>("Top2Sim")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("Timestamp");

                    b.ToTable("DecisionLogEntries");
                });

            modelBuilder.Entity("OmnisRouter.Store.Entities.Install", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Settings")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Installs");
                });

            modelBuilder.Entity("OmnisRouter.Store.Entities.ProviderKey", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ApiKey")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("ApiKeyEncrypted");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("KeyVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Provider");

                    b.ToTable("ProviderKeys");
                });

            modelBuilder.Entity("OmnisRouter.Store.Entities.RouterToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HashedToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HashedToken")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("RouterTokens");
                });

            modelBuilder.Entity("OmnisRouter.Store.Entities.SessionPin", b =>
                {
                    b.Property<string>("SessionKey")
                        .HasColumnType("TEXT");

                    b.Property<int>("ClusterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PinnedModelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PinnedProvider")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SessionKey");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("TenantId");

                    b.ToTable("SessionPins");
                });

            modelBuilder.Entity("OmnisRouter.Store.Entities.Usage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CostUsd")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("CostVsBigUsd")
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<long>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Requests")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Date", "Provider", "ModelId");

                    b.ToTable("Usages");
                });
#pragma warning restore 612, 618
        }
    }
}
